language: scala
scala: 2.12.14
jdk: openjdk8

jobs:
  include:
    - stage: test
      script: sbt headerCheck scalafmtSbtCheck scalafmtCheck test
    - stage: publish
      script: sbt publish
      
stages:  
  - name: test # runs on master commits and PRs
    if: NOT tag =~ ^v
  - name: publish # runs on main repo master commits or version-tagged commits
    if: repo = 2m/kabrioletas AND ( ( branch = master AND type = push ) OR tag =~ ^v )

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers

env:
  global:
    - BINTRAY_USER=2m
    # travis encrypt BINTRAY_PASS=...
    - secure: "Qcpoc09QjK9MnQj4TOLGy3nDMnnBQ6bYsUqCHZWLTh63m3iB2e6HuJMl0E2R1M1qs/nE+hDaeRZlo8qgH1m97qY180sLRgAcpSRzj4rkrrrsxi6pUHBxAK7oUtVt+1ZrPbSeBeYEOarDzd2Vphm5ZQELKG8WhayWXUnDYgcyI1ykFE6TZfNNN4mlNkBLeT2+Vxd8MCS9zY6ygSPYbiJN1l/NYbZAyTMSDofQ0JHdwWr93sE2R4chf6FJumsFTInxVLtFXIVcR8wC6OpsPJ+hu4eyQ/c8DRlZ0ifjxILABoMsfuoGl3WCnR/8noiOpgbV94/l+Aqq46i3U469pxz3YuyBUBsBKUSOzGRqI8T98VIPuZijhzcfWINkk1NxKmQazlzd7DrP97YFOmsU80xNB9fz1z9KUkV59RYnv8k2W8iOXqbwdj/xhTWdt931rNN/mvhUSyLywKtOdCFFxKNatqM4B4wwPNq1KqXX4P9i5PcjJbjbqAahiPyQCwcRuM028vPwTdPY4ZWPzQ5vNwiz3RNSCboCwbH0g+e3Lt/YQtI/vkBG1SeMEIVIH1/2t4L3VOdCB90QlYimL6Huigo9eQe0HCTNlLky08QuYoTADtnndddADkJ8/HB5fD9b5Lm0LX1DF809uvm+cvhj/+D9UzLot1jx6cuNGkYZVA4OEC8="
